[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "whyd"
version = "0.1.4"
description = "CLI time tracker for What Have You Done?!"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
dependencies = [
    "requests",
    "rich",
    "python-dotenv",
]

[project.scripts]
whyd = "whyd:main"

[tool.setuptools]
py-modules = ["whyd"]
